on:
  push
name: build
jobs:
  build:
    runs-on: [self-hosted, linux, x64, ci-cloud]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: build
        run: make html
